name: hello
 on:
   push:
     branches:[main]

     jobs:

       greet:
         run-on: ubuntu:latest

           steps:
             - name: saychello to user
               run: echo"hello bhai"
