name: CICD

on:
  workflow_dispatch:
    inputs:
      enviranment:
        description: This is enviranment value where this workflow Run
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - stg
jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: chechout code
        run: echo "code clone from Github"
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: build Docker container
        run: echo "Docker container build"
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Test the container
        run: echo "Test the container"
  deply:
    if: inputs.enviranment == 'stg'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: deply
        run: echo "Deply the code"
  
