name: CICD

on:
  workflow_dispatch:

jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: chechout code
        run: echo "code clone from Github"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build Docker container
        run: echo "Docker container build"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test the container
        run: echo "Test the container"
  deply:
    runs-on: ubuntu-latest
    steps:
      - name: deply
        run: echo "Deply the code"
  
