name: CIDC1
  on:
   workflow_dispatch:

   jobs:
   code:
     run-on: ubuntu-latest
     steps:
       - nmae: checkout code
         run: echo"code clone from githab"
   build:
      run-on: ubuntu-latest
      steps:
       - nmae: build the container
         run: echo"container build"
   Test:
     run-on: ubuntu-latest
     steps:
       - nmae: test the code
         run: echo"Test the container"
   deply:
      run-on: ubuntu-latest
      steps:
       - nmae: deply code
         run: echo"Deply the code"
