name: CIDC1

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "Code clone from GitHub"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the container
        run: echo "Container build"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test the code
        run: echo "Test the container"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code
        run: echo "Deploy the code"
