name: helloo
  on:
    push:
      branch: [main]
jobs:
  greet:
    run-on: ubuntu-latest
    steps:
      - name: say hello to user
        run: echo "hello Dosts"
  datils:
    run-on: ubuntu-latest
    steps:
        - name: show the python version and docker
          run: python --version & docker --version
