name: helloo

on:
  push:
    branches: [ main ]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to user
        run: echo "hello Dosts"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: Show the python version and docker
        run: |
          python --version
          docker --version
