name: portfolio

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.pages_url }}

    steps:
      # Step 1
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      # Step 3
      - name: Upload static files
        uses: actions/upload-pages-artifact@v4
        with:
          path: "."

      # Step 4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
